apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:  # specification of the pod's contents
  restartPolicy: Never
  volumes: 
  - name: mystorage
    persistentVolumeClaim:
      claimName: nfs-ks-pvc
  containers:
  - name: hello
    image: "ubuntu:14.04"
    command: ["/bin/bash"]
    args: ["-c","echo hello world again > /data/kevin2/myoutput.txt"]
    volumeMounts:
    - mountPath: "/data"
      name: mystorage 
    securityContext:
      runAsUser: 76862
      runAsGroup: 7610