apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: shared  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 0.0.0.0
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared  
  resources:
    requests:
      storage: 8Gi
